# Tuple containing the game notes and their corresponding 'note-wheel' position
notes: tuple = (
    ("A", 0),
    ("A#", 1),
    ("Bb", 1),
    ("B", 2),
    ("C", 3),
    ("C#", 4),
    ("Db", 4),
    ("D", 5),
    ("D#", 6),
    ("Eb", 6),
    ("E", 7),
    ("F", 8),
    ("F#", 9),
    ("Gb", 9),
    ("G", 10),
    ("G#", 11),
    ("Ab", 11),
)