# Generated by Django 4.2.7 on 2023-11-30 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_stsus_post_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="autor",
            new_name="author",
        ),
    ]
